#!/usr/bin/env bash
# Generates the GitHub Release body for ai-engkit.
#
# Usage: release-body.sh <TAG> <FOOTER> [CRITICAL_COUNT]
#
#   TAG            release tag, e.g. v1.11.4
#   FOOTER         italic footer text, e.g. "Generated by GitHub Actions"
#   CRITICAL_COUNT number of critical findings from the vulnerability scan job.
#   HIGH_COUNT, MEDIUM_COUNT, and LOW_COUNT are supplied through the environment.
#
# The Changes section prefers the curated docs/CHANGELOG.md section for this
# version; falls back to raw `git log` when the section does not exist yet
# (e.g. auto-tagged dependency updates that have not staged a CHANGELOG entry).
# Appends a `body` multi-line output to $GITHUB_OUTPUT.
set -euo pipefail

TAG="$1"
FOOTER="$2"
CRITICAL_COUNT="${3:-}"
HIGH_COUNT="${HIGH_COUNT:-}"
MEDIUM_COUNT="${MEDIUM_COUNT:-}"
LOW_COUNT="${LOW_COUNT:-}"

VERSION_NO_V="${TAG#v}"

# The V2 line installs from its own compose/env, so its quick start differs.
if [[ "$TAG" == v2.* ]]; then
  QUICK_START=(
    'curl -fsSL https://raw.githubusercontent.com/tryweb/ai-engkit/v2/install-v2.sh | bash'
  )
else
  QUICK_START=(
    'cp .env.example .env'
    'docker compose up -d'
  )
fi

# A v2 release changes relative to the previous v2 tag, not the v1 line's tags.
if [[ "$TAG" == v2.* ]]; then
  PREV_TAG=$(git tag --sort=-version:refname | \
    grep -E '^v2\.[0-9]+\.[0-9]+$' | \
    grep -v "^${TAG}$" | \
    head -1 || true)
else
  PREV_TAG=$(git tag --sort=-version:refname | \
    grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | \
    grep -vE '(rc|beta|alpha|dev|test|pre)' | \
    grep -v "^${TAG}$" | \
    head -1 || true)
fi

if [ -z "$PREV_TAG" ]; then
  SINCE_TAG="first release"
else
  SINCE_TAG="${PREV_TAG}"
fi

# Prefer the curated CHANGELOG section for this version.
CHANGELOG=""
if [ -f docs/CHANGELOG.md ]; then
  CHANGELOG=$(awk -v v="$VERSION_NO_V" '
    index($0, "## [" v "] - ") == 1 {found=1; next}
    found && /^## \[/ {exit}
    found {print}
  ' docs/CHANGELOG.md || true)
fi

# Fall back to raw git log when the CHANGELOG section is missing.
if [ -z "$CHANGELOG" ]; then
  if [ -z "$PREV_TAG" ]; then
    CHANGELOG=$(git log --oneline --no-merges | head -50 || true)
  else
    CHANGELOG=$(git log "${PREV_TAG}..HEAD" --oneline --no-merges | head -50 || true)
  fi
fi

{
  echo 'body<<RELEASE_BODY_EOF'
  echo '## Docker Image'
  echo ''
  echo '```bash'
  echo "docker pull ghcr.io/${GITHUB_REPOSITORY,,}:${TAG}"
  echo '```'
  echo ''
  echo '## Quick Start'
  echo ''
  echo '```bash'
  for line in "${QUICK_START[@]}"; do echo "$line"; done
  echo '```'
  echo ''
  echo "## Changes (since ${SINCE_TAG})"
  echo ''
  echo "$CHANGELOG"
  echo ''
  echo '## Test Results'
  echo ''
  echo '| Job | Status |'
  echo '|-----|--------|'
  echo '| Integration Tests | ✅ Passed |'
  if [ -z "$CRITICAL_COUNT" ]; then
    echo '| Vulnerability Scan | ⚪ Scan not run |'
  else
    echo '| Vulnerability Scan | ✅ No new Critical/High findings |'
    echo ''
    echo '### Vulnerability findings by severity'
    echo ''
    echo '| Severity | Findings |'
    echo '|----------|---------:|'
    echo "| Critical | ${CRITICAL_COUNT} |"
    echo "| High | ${HIGH_COUNT:-0} |"
    echo "| Medium | ${MEDIUM_COUNT:-0} |"
    echo "| Low | ${LOW_COUNT:-0} |"
  fi
  echo ''
  echo '---'
  echo "*${FOOTER}*"
  echo 'RELEASE_BODY_EOF'
} >> "$GITHUB_OUTPUT"
